### ISSUE TITLE
code to create the MELD and IEMOCAP pickle file

### ISSUE THREAD

**Issue by enastarawneh** [RaleLee/DialogueGCN#2]
I cant get a hold of the code to create the MELD and IEMOCAP pickle file, do you mind sharing it ?

**Comment by RaleLee** [comment]
You can find code for IEMOCAP in the original repo https://github.com/declare-lab/conv-emotion/tree/master/DialogueGCN.
MELD maybe in https://github.com/declare-lab/conv-emotion/tree/master/DialogueRNN.
DialogueRNN and GCN use the same preprocessing code.

**Comment by enastarawneh** [comment]
There is no code for preprocessing in the original repo, I looked everywher. The iemocap features in the pickle file have a different emotion distribution than the original form, to compare to my work I have to recreate the pickle file with no balancing of classes. 

So I was wondering if you could share the preprocessing code so I can change it to adapt to my problem.

**Comment by RaleLee** [comment]
I only ran the DialogueGCN model on DailyDialog and Mastodon. And I created the pickle file by adapting the original code to these two datasets. (See preprocessing code in my repo)
Maybe you can try to modify those code in original repo or in mine. : )

**Comment by enastarawneh** [comment]
Okay thanks
