### ISSUE TITLE
how can i get train_1.json

### ISSUE THREAD

**Issue by ZKayell** [RaleLee/DialogueGCN#3]
hello. i noticed that the dataset you used was in JSON format, but the dataset i downloaded from the official website was in TXT format. How can I convert it to JSON format? Thanks a lot.

`   train_data = create_utterances('dailydialog/train_1.json', 'train')
    valid_data = create_utterances('dailydialog/dev_1.json', 'valid')
    test_data = create_utterances('dailydialog/test_1.json', 'test')`

**Comment by RaleLee** [comment]
You can get the json format dataset here : )
https://github.com/declare-lab/RECCON/tree/main/data/original_annotation

**Comment by ZKayell** [comment]
Thank you so much!
