### ISSUE TITLE
High Overfitting Probability Issue

### ISSUE THREAD

**Issue by Salihcan29** [RaleLee/DialogueGCN#6]
I've constructed a multilabel structure working with the DialogueGCN model. I've also tried connecting different encoders like DistilBERT and TinyBERT to the first layer of the model. Additionally, I experimented with the encoders in both trainable and non-trainable formats. I couldn't surpass a 99% train_f1 score and a 60% validation score. However, I need to point out that I am not using the model as a sentiment model but as a classification model. On average, my dialogues contain 6 utterances, and only 3 or 4 utterances are marked or multi-marked. I trained on 2400 dialogues and approximately 14,000 utterances, and despite playing with all the parameters, I'm encountering high overfitting. I'm wondering if this is due to a mistake in my model architecture or if the model's capacity is primarily sentiment-focused.

**Comment by RaleLee** [comment]
This repo is only a personal preprocess of DialogueGCN model.
For further questions please contact the authors of DialogueGCN : )

**Comment by Salihcan29** [comment]
Thank you for your answer.
